import assert from 'node:assert/strict'
import {describe,it} from 'node:test'
import {endpoints} from '../lib/api/endpoints'
import {deliveryApi} from '../lib/api/deliveries'
import {mockDeliveryApi} from '../lib/mock-deliveries'
import {mockOrderApi} from '../lib/mock-orders'
import {ApiError} from '../lib/api/errors'
import {canRead,type Permission} from '../lib/workspaces'

describe('F9 Delivery Jobs and Attempts',()=>{
 it('builds exactly eight B8.1 operations',()=>{assert.equal(endpoints.deliveries.list('m 1'),'/merchants/m%201/deliveries');assert.equal(endpoints.deliveries.item('m','d/1'),'/merchants/m/deliveries/d%2F1');for(const [name,suffix] of [['ready','ready'],['dispatch','dispatch'],['cancel','cancel'],['attempts','attempts']] as const)assert.equal(endpoints.deliveries[name]('m','d'),`/merchants/m/deliveries/d/${suffix}`);for(const key of ['list','create','detail','ready','dispatch','cancel','attempts','recordAttempt'] as const)assert.equal(typeof deliveryApi[key],'function')})
 it('creates from a CONFIRMED frozen snapshot idempotently and enforces one per Order',async()=>{const order=await mockOrderApi.detail('dstyle','order-confirmed-expired'),created=await mockDeliveryApi.create('dstyle',order.id,'create-one'),replay=await mockDeliveryApi.create('dstyle',order.id,'create-one');assert.equal(created.id,replay.id);assert.equal(created.status,'PENDING');assert.deepEqual([created.recipientNameSnapshot,created.areaSnapshot,created.landmarkSnapshot],[order.customerNameSnapshot,order.deliveryAreaSnapshot,order.deliveryLandmarkSnapshot]);await assert.rejects(()=>mockDeliveryApi.create('dstyle',order.id,'different-key'),(e:unknown)=>e instanceof ApiError&&e.status===409)})
 it('rejects missing location and ineligible Draft/Cancelled Orders',async()=>{for(const [id,key] of [['order-confirmed-no-location','no-location'],['order-draft-sarah','draft'],['order-cancelled','cancelled']] as const)await assert.rejects(()=>mockDeliveryApi.create('dstyle',id,key),(e:unknown)=>e instanceof ApiError&&e.status===422)})
 it('keeps snapshots independent from reusable records and Order state',async()=>{const d=await mockDeliveryApi.detail('dstyle','delivery-pending'),before={...d};assert.deepEqual(d,before);assert.equal((await mockOrderApi.detail('dstyle','order-confirmed-expired')).status,'CONFIRMED')})
 it('runs PENDING to READY to DISPATCHED with desired-state timestamp replay',async()=>{const ready=await mockDeliveryApi.ready('dstyle','delivery-pending'),readyReplay=await mockDeliveryApi.ready('dstyle','delivery-pending');assert.equal(ready.status,'READY');assert.equal(ready.readyAt,readyReplay.readyAt);const dispatched=await mockDeliveryApi.dispatch('dstyle','delivery-pending'),dispatchReplay=await mockDeliveryApi.dispatch('dstyle','delivery-pending');assert.equal(dispatched.status,'DISPATCHED');assert.equal(dispatched.dispatchedAt,dispatchReplay.dispatchedAt);await assert.rejects(()=>mockDeliveryApi.dispatch('dstyle','delivery-cancelled'),ApiError)})
 it('cancels only PENDING/READY and preserves terminal timestamp',async()=>{const p=await mockDeliveryApi.cancel('dstyle','delivery-ready'),again=await mockDeliveryApi.cancel('dstyle','delivery-ready');assert.equal(p.status,'CANCELLED');assert.equal(p.cancelledAt,again.cancelledAt);await assert.rejects(()=>mockDeliveryApi.cancel('dstyle','delivery-dispatched'),ApiError)})
 it('records DELIVERED atomically, normalizes note, replays, and keeps Order independent',async()=>{const key='delivered-attempt',result=await mockDeliveryApi.recordAttempt('dstyle','delivery-dispatched',{result:'DELIVERED',note:'  At reception  '},key),replay=await mockDeliveryApi.recordAttempt('dstyle','delivery-dispatched',{result:'DELIVERED',note:'At reception'},key);assert.equal(result.attempt.id,replay.attempt.id);assert.equal(result.delivery.status,'DELIVERED');assert.equal(result.delivery.deliveredAt,result.attempt.attemptedAt);assert.equal(result.attempt.note,'At reception');assert.equal((await mockDeliveryApi.attempts('dstyle','delivery-dispatched')).pagination.total,1)})
 it('records structured FAILED atomically and validates result/reason/note',async()=>{const result=await mockDeliveryApi.recordAttempt('dstyle','delivery-dispatched-fail',{result:'FAILED',failureReason:'CUSTOMER_UNREACHABLE',note:'  No answer  '},'failed-one');assert.equal(result.delivery.status,'FAILED');assert.equal(result.delivery.failedAt,result.attempt.attemptedAt);assert.equal(result.attempt.failureReason,'CUSTOMER_UNREACHABLE');assert.equal(result.attempt.note,'No answer');await assert.rejects(()=>mockDeliveryApi.recordAttempt('dstyle','delivery-delivered',{result:'FAILED',failureReason:'OTHER'},'terminal'),ApiError);await assert.rejects(()=>mockDeliveryApi.recordAttempt('dstyle','delivery-failed',{result:'FAILED',failureReason:'OTHER',note:'x'.repeat(501)},'long'),ApiError)})
 it('lists newest-first safe attempts and supports exact filters',async()=>{const r=await mockDeliveryApi.attempts('dstyle','delivery-failed',{result:'FAILED',failureReason:'CUSTOMER_UNREACHABLE'});assert.equal(r.attempts[0].attemptNumber,1);const json=JSON.stringify(r);for(const f of ['idempotencyKey','requestHash','merchantId'])assert.equal(json.includes(f),false)})
 it('supports bounded snapshot search, exact status, and inclusive/exclusive dates',async()=>{const r=await mockDeliveryApi.list('dstyle',{q:'Kira Road',status:'DELIVERED',createdFrom:'2026-08-14T09:00:00.000Z',createdTo:'2026-08-14T09:00:01.000Z'});assert.deepEqual(r.deliveries.map(d=>d.id),['delivery-delivered']);assert.equal((await mockDeliveryApi.list('dstyle',{orderId:'delivery-order-delivered',createdTo:'2026-08-14T09:00:00.000Z'})).deliveries.length,0)})
 it('keeps delivery permissions exact and cross-domain independent',()=>{const read:readonly Permission[]=['DELIVERIES_READ'],manage:readonly Permission[]=['DELIVERIES_MANAGE'],both:readonly Permission[]=['DELIVERIES_READ','DELIVERIES_MANAGE'];assert.equal(canRead('DELIVERIES_READ',read),true);assert.equal(canRead('DELIVERIES_MANAGE',read),false);assert.equal(canRead('DELIVERIES_READ',manage),false);assert.equal(canRead('DELIVERIES_MANAGE',manage),true);for(const p of ['ORDERS_MANAGE','PAYMENTS_MANAGE','INVENTORY_MANAGE'] as const)assert.equal(canRead(p,both),false)})
 it('live failures never fall back to mock Deliveries',async()=>{await assert.rejects(()=>deliveryApi.list('dstyle'),(e:unknown)=>e instanceof ApiError)})
})
