'use client'

import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useCallback, useEffect, useState } from 'react'
import { AlertCircle, Plus, Search, Users } from 'lucide-react'
import { AppShell, PageHeader, StatusPill } from '@/components/app-shell'
import { AccessDenied } from '@/components/workspace-access'
import { CustomerFormDialog } from '@/components/customers/customer-form-dialog'
import { PaginationControls } from '@/components/catalogue/pagination-controls'
import { useMerchantWorkspace } from '@/components/merchant-workspace-provider'
import { customersService } from '@/lib/customers-service'
import type { Customer, CustomerStatus } from '@/lib/api/customers'
import { ApiError } from '@/lib/api/errors'
import { useToast } from '@/components/ui/toast'

const friendlyError = (error: unknown, fallback: string) => error instanceof ApiError && error.status === 409 ? 'A customer with this phone number already exists.' : fallback
export default function CustomersPage(){return <AppShell><CustomersContent/></AppShell>}
function CustomersContent(){const {workspace,hasPermission}=useMerchantWorkspace();const canRead=hasPermission('CUSTOMERS_READ'),canManage=hasPermission('CUSTOMERS_MANAGE');if(!canRead)return <><PageHeader eyebrow="Commerce" title="Customers" description="Keep customer contact details and delivery locations in one place."/><AccessDenied title="You do not have access to Customers."/></>;return <CustomerDirectory merchantId={workspace.id} canManage={canManage}/>}
function CustomerDirectory({merchantId,canManage}:{merchantId:string;canManage:boolean}){
 const router=useRouter();const {toast}=useToast();const [rows,setRows]=useState<Customer[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[q,setQ]=useState(''),[status,setStatus]=useState<''|CustomerStatus>(''),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(20),[total,setTotal]=useState(0),[totalPages,setTotalPages]=useState(1),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');try{const result=await customersService().list(merchantId,{q:q.trim()||undefined,status:status||undefined,page,pageSize});setRows(result.customers);setTotal(result.pagination.total);setTotalPages(result.pagination.totalPages)}catch{setError('Unable to load customers.')}finally{setLoading(false)}},[merchantId,q,status,page,pageSize]);useEffect(()=>{const timer=setTimeout(()=>void load(),q?250:0);return()=>clearTimeout(timer)},[load,q])
 const create=async(input:{name:string|null;phone:string})=>{setSaving(true);setSaveError('');try{const created=await customersService().create(merchantId,input);setOpen(false);toast('Customer added.');router.push(`/app/customers/${created.id}`)}catch(e){setSaveError(friendlyError(e,"We couldn't save this customer."))}finally{setSaving(false)}}
 const filters=!!q||!!status
 return <><PageHeader eyebrow="Commerce" title="Customers" description="Keep customer contact details and delivery locations in one place." action={canManage?<button id="add-customer-btn" onClick={()=>setOpen(true)} className="inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground"><Plus className="size-4"/>Add Customer</button>:undefined}/><div className="mb-5 flex flex-col gap-3 rounded-xl border border-border bg-card p-4 sm:flex-row"><label className="relative flex-1"><span className="sr-only">Search customers</span><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Search by name or phone" className="h-10 w-full rounded-lg border border-input bg-background pl-10 pr-3 text-sm"/></label><label><span className="sr-only">Customer status</span><select value={status} onChange={e=>{setStatus(e.target.value as ''|CustomerStatus);setPage(1)}} className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm sm:w-44"><option value="">All statuses</option><option value="ACTIVE">Active</option><option value="ARCHIVED">Archived</option></select></label></div>{loading?<CustomerSkeleton/>:error?<div role="alert" className="flex min-h-56 flex-col items-center justify-center rounded-2xl border border-border bg-card p-8 text-center"><AlertCircle className="size-9 text-destructive"/><p className="mt-3 font-semibold">{error}</p><button onClick={()=>void load()} className="mt-4 rounded-lg border border-border px-4 py-2 text-sm font-semibold">Try again</button></div>:rows.length===0?<div className="flex min-h-56 flex-col items-center justify-center rounded-2xl border border-dashed border-border bg-card p-8 text-center"><Users className="size-10 text-muted-foreground"/><p className="mt-3 font-semibold">{filters?'No customers match your search.':'No customers yet.'}</p><p className="mt-2 text-sm text-muted-foreground">{filters?'Try changing or clearing your filters.':'Add a customer when you receive an enquiry or order.'}</p>{filters&&<button onClick={()=>{setQ('');setStatus('')}} className="mt-4 rounded-lg border border-border px-4 py-2 text-sm font-semibold">Clear filters</button>}</div>:<><CustomerList rows={rows}/><PaginationControls pagination={{page,pageSize,total,totalPages}} onPageChange={setPage} onPageSizeChange={size=>{setPageSize(size);setPage(1)}} itemName="customer"/></>}<CustomerFormDialog open={open} submitting={saving} serverError={saveError} onClose={()=>{setOpen(false);setSaveError('')}} onSave={create}/></>
}
function CustomerList({rows}:{rows:Customer[]}){return <><div className="hidden overflow-hidden rounded-xl border border-border bg-card md:block"><table className="w-full text-left text-sm"><thead className="bg-secondary/60 text-xs uppercase tracking-wider text-muted-foreground"><tr><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Phone</th><th className="px-5 py-3">Status</th><th className="px-5 py-3"><span className="sr-only">Open</span></th></tr></thead><tbody className="divide-y divide-border">{rows.map(c=><tr key={c.id}><td className="px-5 py-4 font-semibold">{c.name||'Unnamed customer'}</td><td className="px-5 py-4"><a href={`tel:${c.phone}`} className="hover:underline">{c.phone}</a></td><td className="px-5 py-4"><StatusPill status={c.status==='ACTIVE'?'Active':'Archived'}/></td><td className="px-5 py-4 text-right"><Link href={`/app/customers/${c.id}`} className="font-semibold text-primary hover:underline">View customer</Link></td></tr>)}</tbody></table></div><div className="grid gap-3 md:hidden">{rows.map(c=><Link key={c.id} href={`/app/customers/${c.id}`} className="rounded-xl border border-border bg-card p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{c.name||'Unnamed customer'}</p><p className="mt-1 text-sm text-muted-foreground">{c.phone}</p></div><StatusPill status={c.status==='ACTIVE'?'Active':'Archived'}/></div></Link>)}</div></>}
function CustomerSkeleton(){return <div aria-label="Loading customers" className="space-y-3">{[1,2,3].map(i=><div key={i} className="h-20 animate-pulse rounded-xl border border-border bg-secondary/50"/>)}</div>}
