import { ApiError } from './api/errors'
import type { PaymentListQuery, PaymentListResponse, PaymentSummary, PaymentTransaction, ProviderVerifyResponse, ReportPaymentInput, VerificationAttempt, VerificationAttemptListQuery, VerificationAttemptListResponse, VerificationAttemptStatus } from './api/payments'
import { mockOrderApi } from './mock-orders'

const stamp='2026-08-13T10:00:00.000Z'
let sequence=300
const rows:PaymentTransaction[]=[
  {id:'pay-partial-cash',orderId:'order-confirmed-expired',method:'CASH',status:'VERIFIED',verificationSource:'MANUAL',amount:'30000',currency:'UGX',payerPhone:null,providerReference:null,merchantReference:'Till-41',note:'Deposit',reportedAt:stamp,verificationPendingAt:null,verifiedAt:stamp,rejectedAt:null,failedAt:null,reversedAt:null,refundedAt:null,createdAt:stamp,updatedAt:stamp},
  {id:'pay-reported-mtn',orderId:'order-confirmed-expired',method:'MTN_MOMO',status:'REPORTED',verificationSource:null,amount:'55000',currency:'UGX',payerPhone:'+256772123456',providerReference:'MP-2041',merchantReference:null,note:null,reportedAt:stamp,verificationPendingAt:null,verifiedAt:null,rejectedAt:null,failedAt:null,reversedAt:null,refundedAt:null,createdAt:stamp,updatedAt:stamp},
  {id:'pay-pending-airtel',orderId:'order-draft-sarah',method:'AIRTEL_MONEY',status:'VERIFICATION_PENDING',verificationSource:null,amount:'40000',currency:'UGX',payerPhone:'+256701555010',providerReference:null,merchantReference:null,note:null,reportedAt:stamp,verificationPendingAt:stamp,verifiedAt:null,rejectedAt:null,failedAt:null,reversedAt:null,refundedAt:null,createdAt:stamp,updatedAt:stamp},
  {id:'pay-overpaid-one',orderId:'order-abandoned',method:'CASH',status:'VERIFIED',verificationSource:'MANUAL',amount:'100000',currency:'UGX',payerPhone:null,providerReference:null,merchantReference:null,note:null,reportedAt:stamp,verificationPendingAt:null,verifiedAt:stamp,rejectedAt:null,failedAt:null,reversedAt:null,refundedAt:null,createdAt:stamp,updatedAt:stamp},
  {id:'pay-rejected-history',orderId:'order-cancelled',method:'MTN_MOMO',status:'REJECTED',verificationSource:null,amount:'70000',currency:'UGX',payerPhone:'+256752404040',providerReference:'NO-MATCH',merchantReference:null,note:null,reportedAt:stamp,verificationPendingAt:null,verifiedAt:null,rejectedAt:stamp,failedAt:null,reversedAt:null,refundedAt:null,createdAt:stamp,updatedAt:stamp},
  {id:'pay-provider-verified',orderId:'order-cancelled',method:'MTN_MOMO',status:'VERIFIED',verificationSource:'PROVIDER',amount:'15000',currency:'UGX',payerPhone:'+256772000111',providerReference:'VERIFY-HISTORY',merchantReference:null,note:null,reportedAt:'2026-08-13T08:30:00.000Z',verificationPendingAt:null,verifiedAt:'2026-08-13T08:31:00.000Z',rejectedAt:null,failedAt:null,reversedAt:null,refundedAt:null,createdAt:'2026-08-13T08:30:00.000Z',updatedAt:'2026-08-13T08:31:00.000Z'},
]
const keys=new Map<string,{hash:string;paymentId:string}>()
let attemptSequence=500
const attempts:Record<string,VerificationAttempt[]>={
  'pay-reported-mtn':[
    {id:'attempt-unavailable',provider:'MTN_MOMO',status:'FAILED',providerTransactionId:null,providerStatusCode:null,providerStatusText:null,failureCode:'PROVIDER_VERIFICATION_UNAVAILABLE',failureMessage:'No provider verification adapter is configured.',requestedAt:'2026-08-13T09:10:00.000Z',completedAt:'2026-08-13T09:10:01.000Z',createdAt:'2026-08-13T09:10:00.000Z'},
    {id:'attempt-failed',provider:'MTN_MOMO',status:'FAILED',providerTransactionId:null,providerStatusCode:'TIMEOUT',providerStatusText:'Provider timeout',failureCode:'ADAPTER_ERROR',failureMessage:'Provider verification failed.',requestedAt:'2026-08-13T09:00:00.000Z',completedAt:'2026-08-13T09:00:02.000Z',createdAt:'2026-08-13T09:00:00.000Z'},
  ],
  'pay-pending-airtel':[{id:'attempt-not-verified',provider:'AIRTEL_MONEY',status:'NOT_VERIFIED',providerTransactionId:null,providerStatusCode:'NOT_FOUND',providerStatusText:'No matching transaction',failureCode:null,failureMessage:null,requestedAt:'2026-08-13T08:00:00.000Z',completedAt:'2026-08-13T08:00:01.000Z',createdAt:'2026-08-13T08:00:00.000Z'}],
  'pay-provider-verified':[{id:'attempt-verified-history',provider:'MTN_MOMO',status:'VERIFIED',providerTransactionId:'provider-history-1',providerStatusCode:'SUCCESS',providerStatusText:'Matched',failureCode:null,failureMessage:null,requestedAt:'2026-08-13T08:30:00.000Z',completedAt:'2026-08-13T08:31:00.000Z',createdAt:'2026-08-13T08:30:00.000Z'}],
}
const providerKeys=new Map<string,{hash:string;attemptId:string}>()
const providerCalls=new Map<string,number>()
export type MockProviderOutcome='VERIFIED'|'NOT_VERIFIED'|'FAILED'|'UNAVAILABLE'
const outcomeByReference=(reference:string):MockProviderOutcome=>reference.startsWith('VERIFY-')?'VERIFIED':reference.startsWith('NO-MATCH')?'NOT_VERIFIED':reference.startsWith('FAIL-')?'FAILED':'UNAVAILABLE'
const normalizePhone=(value:string)=>{const clean=value.replace(/[\s()-]/g,'');if(/^0[7][0-9]{8}$/.test(clean))return`+256${clean.slice(1)}`;if(/^\+2567[0-9]{8}$/.test(clean))return clean;throw new ApiError({status:400,message:'payerPhone must be a valid Uganda phone number.'})}
const find=(merchantId:string,orderId:string,paymentId:string)=>{if(merchantId!=='dstyle')throw new ApiError({status:404,message:'Not found.'});const row=rows.find(item=>item.orderId===orderId&&item.id===paymentId);if(!row)throw new ApiError({status:404,message:'Not found.'});return row}
const summary=async(orderId:string):Promise<PaymentSummary>=>{const order=await mockOrderApi.detail('dstyle',orderId),verified=rows.filter(item=>item.orderId===orderId&&item.status==='VERIFIED').reduce((sum,item)=>sum+BigInt(item.amount),BigInt(0)),amount=BigInt(order.subtotal);let status:PaymentSummary['status']='UNPAID',due=amount,over=BigInt(0);if(verified>BigInt(0)&&verified<amount){status='PARTIALLY_PAID';due=amount-verified}else if(verified===amount&&verified>BigInt(0)){status='PAID';due=BigInt(0)}else if(verified>amount){status='OVERPAID';due=BigInt(0);over=verified-amount}return{orderId,currency:order.currency,orderAmount:order.subtotal,verifiedAmount:verified.toString(),amountDue:due.toString(),overpaidAmount:over.toString(),status}}
export const mockPaymentApi={
  async list(merchantId:string,orderId:string,query:PaymentListQuery={}):Promise<PaymentListResponse>{await mockOrderApi.detail(merchantId,orderId);const page=query.page??1,pageSize=query.pageSize??20;const filtered=rows.filter(item=>item.orderId===orderId&&(!query.method||item.method===query.method)&&(!query.status||item.status===query.status)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||b.id.localeCompare(a.id));return{items:filtered.slice((page-1)*pageSize,page*pageSize),page,pageSize,total:filtered.length}},
  async report(merchantId:string,orderId:string,input:ReportPaymentInput,key:string){const order=await mockOrderApi.detail(merchantId,orderId);if(!['DRAFT','CONFIRMED'].includes(order.status)||!order.currency||order.subtotal==='0')throw new ApiError({status:422,message:'Order cannot accept a payment report.'});if(!/^\d+$/.test(input.amount)||BigInt(input.amount)<=BigInt(0)||BigInt(input.amount)>BigInt('9223372036854775807'))throw new ApiError({status:400,message:'Invalid Payment report.'});if(input.method==='CASH'&&input.providerReference)throw new ApiError({status:400,message:'Cash payments cannot have a provider reference.'});const payerPhone=input.payerPhone?normalizePhone(input.payerPhone):null;if(input.method!=='CASH'&&!payerPhone)throw new ApiError({status:400,message:'Mobile Money payments require payerPhone.'});const canonical={...input,payerPhone,providerReference:input.providerReference?.trim()||null,merchantReference:input.merchantReference?.trim()||null,note:input.note?.trim()||null},hash=JSON.stringify([orderId,canonical]),scoped=`${merchantId}:${key}`,saved=keys.get(scoped);if(saved){if(saved.hash!==hash)throw new ApiError({status:409,message:'Payment idempotency key conflict.'});return{...find(merchantId,orderId,saved.paymentId)}}const now=new Date().toISOString(),row:PaymentTransaction={id:`pay-${++sequence}`,orderId,method:input.method,status:'REPORTED',verificationSource:null,amount:BigInt(input.amount).toString(),currency:order.currency,payerPhone,providerReference:canonical.providerReference,merchantReference:canonical.merchantReference,note:canonical.note,reportedAt:now,verificationPendingAt:null,verifiedAt:null,rejectedAt:null,failedAt:null,reversedAt:null,refundedAt:null,createdAt:now,updatedAt:now};rows.unshift(row);keys.set(scoped,{hash,paymentId:row.id});return{...row}},
  async detail(merchantId:string,orderId:string,paymentId:string){return{...find(merchantId,orderId,paymentId)}},
  async verificationPending(merchantId:string,orderId:string,paymentId:string){return transition(merchantId,orderId,paymentId,'VERIFICATION_PENDING')},
  async verify(merchantId:string,orderId:string,paymentId:string){return transition(merchantId,orderId,paymentId,'VERIFIED')},
  async reject(merchantId:string,orderId:string,paymentId:string){return transition(merchantId,orderId,paymentId,'REJECTED')},
  async providerVerify(merchantId:string,orderId:string,paymentId:string,key:string):Promise<ProviderVerifyResponse>{const row=find(merchantId,orderId,paymentId);if(row.method==='CASH')throw new ApiError({status:422,message:'Provider verification does not apply to this Payment.'});if(!row.providerReference)throw new ApiError({status:422,message:'Provider reference is required for verification.'});const hash=JSON.stringify([paymentId,row.method,row.providerReference,row.payerPhone,row.amount,row.currency]),scoped=`${merchantId}:${key}`,saved=providerKeys.get(scoped);if(saved){if(saved.hash!==hash)throw new ApiError({status:409,message:'Provider verification idempotency key conflict.'});const attempt=(attempts[paymentId]??[]).find(item=>item.id===saved.attemptId)!;if(attempt.failureCode==='PROVIDER_VERIFICATION_UNAVAILABLE')throw new ApiError({status:503,message:'Provider verification is unavailable.'});return{payment:pickResultPayment(row),attempt:{...attempt}}}if(!['REPORTED','VERIFICATION_PENDING'].includes(row.status))throw new ApiError({status:409,message:'Provider verification is not allowed.'});const now=new Date().toISOString(),outcome=outcomeByReference(row.providerReference),attempt:VerificationAttempt={id:`attempt-${++attemptSequence}`,provider:row.method,status:outcome==='UNAVAILABLE'?'FAILED':outcome,providerTransactionId:outcome==='VERIFIED'?`provider-${attemptSequence}`:null,providerStatusCode:outcome==='NOT_VERIFIED'?'NOT_FOUND':outcome==='FAILED'?'TIMEOUT':outcome==='VERIFIED'?'SUCCESS':null,providerStatusText:outcome==='NOT_VERIFIED'?'No matching transaction':outcome==='FAILED'?'Provider timeout':outcome==='VERIFIED'?'Matched':null,failureCode:outcome==='UNAVAILABLE'?'PROVIDER_VERIFICATION_UNAVAILABLE':outcome==='FAILED'?'ADAPTER_ERROR':null,failureMessage:outcome==='UNAVAILABLE'?'No provider verification adapter is configured.':outcome==='FAILED'?'Provider verification failed.':null,requestedAt:now,completedAt:now,createdAt:now};attempts[paymentId]=[attempt,...(attempts[paymentId]??[])];providerKeys.set(scoped,{hash,attemptId:attempt.id});providerCalls.set(paymentId,(providerCalls.get(paymentId)??0)+1);if(outcome==='VERIFIED'&&['REPORTED','VERIFICATION_PENDING'].includes(row.status)){row.status='VERIFIED';row.verificationSource='PROVIDER';row.verifiedAt=now;row.updatedAt=now}if(outcome==='UNAVAILABLE')throw new ApiError({status:503,message:'Provider verification is unavailable.'});return{payment:pickResultPayment(row),attempt:{...attempt}}},
  async verificationAttempts(merchantId:string,orderId:string,paymentId:string,query:VerificationAttemptListQuery={}):Promise<VerificationAttemptListResponse>{find(merchantId,orderId,paymentId);const page=query.page??1,pageSize=query.pageSize??20,filtered=(attempts[paymentId]??[]).filter(item=>!query.status||item.status===query.status).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||b.id.localeCompare(a.id));return{items:filtered.slice((page-1)*pageSize,page*pageSize).map(item=>({...item})),page,pageSize,total:filtered.length}},
  summary:(merchantId:string,orderId:string)=>merchantId==='dstyle'?summary(orderId):Promise.reject(new ApiError({status:404,message:'Not found.'})),
}
function transition(merchantId:string,orderId:string,paymentId:string,target:'VERIFICATION_PENDING'|'VERIFIED'|'REJECTED'){const row=find(merchantId,orderId,paymentId);if(row.status===target)return{...row};const pending=target==='VERIFICATION_PENDING'&&row.method!=='CASH'&&row.status==='REPORTED',verify=target==='VERIFIED'&&(row.status==='REPORTED'||row.status==='VERIFICATION_PENDING'),reject=target==='REJECTED'&&(row.status==='REPORTED'||row.status==='VERIFICATION_PENDING');if(!pending&&!verify&&!reject)throw new ApiError({status:409,message:'Payment transition is not allowed.'});const now=new Date().toISOString();row.status=target;row.updatedAt=now;if(target==='VERIFICATION_PENDING')row.verificationPendingAt=now;if(target==='VERIFIED'){row.verifiedAt=now;row.verificationSource='MANUAL'}if(target==='REJECTED')row.rejectedAt=now;return{...row}}
const pickResultPayment=(row:PaymentTransaction)=>({id:row.id,status:row.status,verificationSource:row.verificationSource,verifiedAt:row.verifiedAt})
export const mockProviderOperationCount=(paymentId:string)=>providerCalls.get(paymentId)??0
