import { ApiError } from './api/errors'
import type { DeliveryAttempt,DeliveryAttemptListQuery,DeliveryAttemptListResponse,DeliveryFailureReason,DeliveryJob,DeliveryListQuery,DeliveryListResponse,DeliveryStatus,RecordDeliveryAttemptInput,RecordDeliveryAttemptResponse } from './api/deliveries'
import { mockOrderApi } from './mock-orders'

const stamp='2026-08-14T09:00:00.000Z'
const base=(id:string,orderId:string,status:DeliveryStatus,name:string,area:string,landmark:string,phone:string):DeliveryJob=>({id,orderId,status,recipientNameSnapshot:name,recipientPhoneSnapshot:phone,deliveryPhoneSnapshot:phone,areaSnapshot:area,landmarkSnapshot:landmark,instructionsSnapshot:'Call when you arrive.',mapPinUrlSnapshot:`https://maps.google.com/?q=${encodeURIComponent(area)}`,createdAt:stamp,updatedAt:stamp,readyAt:['READY','DISPATCHED','DELIVERED','FAILED'].includes(status)?stamp:null,dispatchedAt:['DISPATCHED','DELIVERED','FAILED'].includes(status)?stamp:null,deliveredAt:status==='DELIVERED'?stamp:null,failedAt:status==='FAILED'?stamp:null,cancelledAt:status==='CANCELLED'?stamp:null})
const rows:DeliveryJob[]=[
 base('delivery-pending','delivery-order-pending','PENDING','Grace Atim','Bukoto','Acacia Avenue gate','+256772111001'),
 base('delivery-ready','delivery-order-ready','READY','Moses Kato','Ntinda','Capital Shoppers junction','+256772111002'),
 base('delivery-dispatched','delivery-order-dispatched','DISPATCHED','Irene Nabirye','Muyenga','Tank Hill road','+256772111003'),
 base('delivery-dispatched-fail','delivery-order-dispatched-fail','DISPATCHED','Paul Ssali','Rubaga','Cathedral junction','+256772111007'),
 base('delivery-delivered','delivery-order-delivered','DELIVERED','John Okello','Kira','Kira Road police post','+256772111004'),
 base('delivery-failed','delivery-order-failed','FAILED','Ruth Nambi','Bweyogerere','Jinja Road stage','+256772111005'),
 base('delivery-cancelled','delivery-order-cancelled','CANCELLED','David Ssenyonga','Makindye','Military barracks turn','+256772111006'),
]
const attemptRows:Record<string,DeliveryAttempt[]>={
 'delivery-delivered':[{id:'delivery-attempt-delivered',deliveryJobId:'delivery-delivered',attemptNumber:1,result:'DELIVERED',failureReason:null,note:'Handed to the recipient.',attemptedAt:stamp,createdAt:stamp}],
 'delivery-failed':[{id:'delivery-attempt-failed',deliveryJobId:'delivery-failed',attemptNumber:1,result:'FAILED',failureReason:'CUSTOMER_UNREACHABLE',note:'Phone rang without an answer.',attemptedAt:stamp,createdAt:stamp}],
}
let sequence=800
const createKeys=new Map<string,{hash:string;deliveryId:string}>(),attemptKeys=new Map<string,{hash:string;deliveryId:string;attemptId:string}>()
const deliveryPersonas=new Set(['dstyle','deliveries-read-only','deliveries-manage-only','deliveries-full-no-orders'])
const domainMerchant=(merchantId:string)=>deliveryPersonas.has(merchantId)?'dstyle':merchantId
const find=(merchantId:string,id:string)=>{if(!deliveryPersonas.has(merchantId))throw new ApiError({status:404,message:'Not found.'});const row=rows.find(item=>item.id===id);if(!row)throw new ApiError({status:404,message:'Not found.'});return row}
const copy=(row:DeliveryJob)=>({...row})
const pagination=(page:number,pageSize:number,total:number)=>({page,pageSize,total,totalPages:Math.ceil(total/pageSize)})
export const mockDeliveryApi={
 async list(merchantId:string,query:DeliveryListQuery={}):Promise<DeliveryListResponse>{if(!deliveryPersonas.has(merchantId))throw new ApiError({status:404,message:'Not found.'});const page=query.page??1,pageSize=query.pageSize??20,q=query.q?.trim().toLowerCase(),from=query.createdFrom?Date.parse(query.createdFrom):null,to=query.createdTo?Date.parse(query.createdTo):null;const filtered=rows.filter(d=>(!q||[d.recipientNameSnapshot,d.recipientPhoneSnapshot,d.deliveryPhoneSnapshot,d.areaSnapshot,d.landmarkSnapshot].some(v=>v?.toLowerCase().includes(q)))&&(!query.orderId||d.orderId===query.orderId)&&(!query.status||d.status===query.status)&&(from===null||Date.parse(d.createdAt)>=from)&&(to===null||Date.parse(d.createdAt)<to)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||b.id.localeCompare(a.id));return{deliveries:filtered.slice((page-1)*pageSize,page*pageSize).map(copy),pagination:pagination(page,pageSize,filtered.length)}},
 async create(merchantId:string,orderId:string,key:string){const hash=JSON.stringify([orderId]),scoped=`${merchantId}:${key}`,replay=createKeys.get(scoped);if(replay){if(replay.hash!==hash)throw new ApiError({status:409,message:'Idempotency key already used.'});return copy(find(merchantId,replay.deliveryId))}if(rows.some(d=>d.orderId===orderId))throw new ApiError({status:409,message:'Delivery already exists for this order.'});let order;try{order=await mockOrderApi.detail(domainMerchant(merchantId),orderId)}catch{throw new ApiError({status:422,message:'Order is unavailable for delivery.'})}if(order.status!=='CONFIRMED')throw new ApiError({status:422,message:'Order is not eligible for delivery.'});if(!order.deliveryLocationId||!order.deliveryAreaSnapshot||!order.deliveryLandmarkSnapshot||!order.deliveryPhoneSnapshot)throw new ApiError({status:422,message:'A complete Order delivery location is required.'});const now=new Date().toISOString(),row:DeliveryJob={id:`delivery-${++sequence}`,orderId,status:'PENDING',recipientNameSnapshot:order.customerNameSnapshot,recipientPhoneSnapshot:order.customerPhoneSnapshot,areaSnapshot:order.deliveryAreaSnapshot,landmarkSnapshot:order.deliveryLandmarkSnapshot,deliveryPhoneSnapshot:order.deliveryPhoneSnapshot,instructionsSnapshot:order.deliveryInstructionsSnapshot,mapPinUrlSnapshot:order.deliveryMapPinUrlSnapshot,createdAt:now,updatedAt:now,readyAt:null,dispatchedAt:null,deliveredAt:null,failedAt:null,cancelledAt:null};rows.unshift(row);createKeys.set(scoped,{hash,deliveryId:row.id});return copy(row)},
 async detail(merchantId:string,deliveryId:string){return copy(find(merchantId,deliveryId))},
 async ready(merchantId:string,deliveryId:string){return transition(merchantId,deliveryId,'READY')},
 async dispatch(merchantId:string,deliveryId:string){return transition(merchantId,deliveryId,'DISPATCHED')},
 async cancel(merchantId:string,deliveryId:string){return transition(merchantId,deliveryId,'CANCELLED')},
 async attempts(merchantId:string,deliveryId:string,query:DeliveryAttemptListQuery={}):Promise<DeliveryAttemptListResponse>{find(merchantId,deliveryId);const page=query.page??1,pageSize=query.pageSize??20,filtered=(attemptRows[deliveryId]??[]).filter(a=>(!query.result||a.result===query.result)&&(!query.failureReason||a.failureReason===query.failureReason)).sort((a,b)=>b.attemptNumber-a.attemptNumber||b.id.localeCompare(a.id));return{deliveryId,attempts:filtered.slice((page-1)*pageSize,page*pageSize).map(a=>({...a})),pagination:pagination(page,pageSize,filtered.length)}},
 async recordAttempt(merchantId:string,deliveryId:string,input:RecordDeliveryAttemptInput,key:string):Promise<RecordDeliveryAttemptResponse>{const row=find(merchantId,deliveryId),note=input.note?.trim()||null;if(note&&note.length>500)throw new ApiError({status:400,message:'Invalid Delivery Attempt request.'});if(input.result==='DELIVERED'&&input.failureReason)throw new ApiError({status:400,message:'Invalid Delivery Attempt request.'});if(input.result==='FAILED'&&!input.failureReason)throw new ApiError({status:400,message:'Invalid Delivery Attempt request.'});const canonical={result:input.result,failureReason:input.result==='FAILED'?input.failureReason:null,note},hash=JSON.stringify([deliveryId,canonical]),scoped=`${merchantId}:${key}`,saved=attemptKeys.get(scoped);if(saved){if(saved.hash!==hash||saved.deliveryId!==deliveryId)throw new ApiError({status:409,message:'Attempt idempotency key already used.'});return{delivery:copy(row),attempt:{...(attemptRows[deliveryId]??[]).find(a=>a.id===saved.attemptId)!}}}if(row.status!=='DISPATCHED')throw new ApiError({status:409,message:'Delivery transition is not allowed.'});const now=new Date().toISOString(),attempt:DeliveryAttempt={id:`delivery-attempt-${++sequence}`,deliveryJobId:deliveryId,attemptNumber:(attemptRows[deliveryId]?.[0]?.attemptNumber??0)+1,result:input.result,failureReason:canonical.failureReason,note,attemptedAt:now,createdAt:now};attemptRows[deliveryId]=[attempt,...(attemptRows[deliveryId]??[])];row.status=input.result;row.updatedAt=now;if(input.result==='DELIVERED')row.deliveredAt=now;else row.failedAt=now;attemptKeys.set(scoped,{hash,deliveryId,attemptId:attempt.id});return{delivery:copy(row),attempt:{...attempt}}},
}
function transition(merchantId:string,id:string,target:'READY'|'DISPATCHED'|'CANCELLED'){const row=find(merchantId,id);if(row.status===target)return copy(row);const valid=(target==='READY'&&row.status==='PENDING')||(target==='DISPATCHED'&&row.status==='READY')||(target==='CANCELLED'&&['PENDING','READY'].includes(row.status));if(!valid)throw new ApiError({status:409,message:'Delivery transition is not allowed.'});const now=new Date().toISOString();row.status=target;row.updatedAt=now;if(target==='READY')row.readyAt=now;if(target==='DISPATCHED')row.dispatchedAt=now;if(target==='CANCELLED')row.cancelledAt=now;return copy(row)}
