'use client'
import { useEffect,useRef,useState } from 'react'
import { X } from 'lucide-react'
import type { DeliveryAttemptResult,DeliveryFailureReason } from '@/lib/api/deliveries'

export const failureLabels:Record<DeliveryFailureReason,string>={CUSTOMER_UNREACHABLE:'Customer unreachable',CUSTOMER_UNAVAILABLE:'Customer unavailable',CUSTOMER_REFUSED:'Customer refused delivery',WRONG_LOCATION:'Wrong location',ADDRESS_NOT_FOUND:'Address / landmark not found',VEHICLE_OR_RIDER_ISSUE:'Vehicle or rider issue',WEATHER_OR_ACCESS_ISSUE:'Weather or access issue',OTHER:'Other'}
const reasons=Object.keys(failureLabels) as DeliveryFailureReason[]
function Frame({open,title,description,pending,error,onClose,children}:{open:boolean;title:string;description:string;pending:boolean;error:string;onClose:()=>void;children:React.ReactNode}){const first=useRef<HTMLButtonElement>(null);useEffect(()=>{if(open)first.current?.focus()},[open]);useEffect(()=>{if(!open)return;const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!pending)onClose()};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[open,pending,onClose]);if(!open)return null;return <div className="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4"><div role="dialog" aria-modal="true" aria-labelledby="delivery-dialog-title" className="w-full max-w-lg rounded-2xl border border-border bg-background p-6 shadow-xl"><div className="flex justify-between gap-4"><div><h2 id="delivery-dialog-title" className="font-serif text-2xl font-bold">{title}</h2><p className="mt-2 text-sm text-muted-foreground">{description}</p></div><button ref={first} type="button" aria-label="Close dialog" disabled={pending} onClick={onClose}><X className="size-5"/></button></div>{error&&<p role="alert" className="mt-4 rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}{children}</div></div>}
export function ConfirmDeliveryDialog({open,title,description,confirmLabel,pending,error,onClose,onConfirm}:{open:boolean;title:string;description:string;confirmLabel:string;pending:boolean;error:string;onClose:()=>void;onConfirm:()=>void}){return <Frame {...{open,title,description,pending,error,onClose}}><div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" disabled={pending} onClick={onClose} className="h-11 rounded-lg border border-border px-4 font-semibold">Keep Delivery</button><button type="button" disabled={pending} aria-busy={pending} onClick={onConfirm} className="h-11 rounded-lg bg-primary px-4 font-semibold text-primary-foreground disabled:opacity-60">{pending?'Saving…':confirmLabel}</button></div></Frame>}
export function DeliveryAttemptDialog({open,result,pending,error,onClose,onSubmit}:{open:boolean;result:DeliveryAttemptResult;pending:boolean;error:string;onClose:()=>void;onSubmit:(value:{result:DeliveryAttemptResult;failureReason?:DeliveryFailureReason;note:string|null})=>void}){const [reason,setReason]=useState<DeliveryFailureReason>('CUSTOMER_UNREACHABLE'),[note,setNote]=useState('');useEffect(()=>{if(open){setReason('CUSTOMER_UNREACHABLE');setNote('')}},[open]);const delivered=result==='DELIVERED';return <Frame open={open} title={delivered?'Mark this delivery as delivered?':'Record a failed delivery'} description={delivered?'This creates a Delivered Attempt. It does not fulfil the Order or change stock.':'Record the structured outcome for this dispatched delivery. The Order remains unchanged.'} pending={pending} error={error} onClose={onClose}><form className="mt-5 space-y-4" onSubmit={e=>{e.preventDefault();onSubmit({result,...(!delivered?{failureReason:reason}:{}),note:note.trim()||null})}}>{!delivered&&<label className="block text-sm font-medium">Failure reason<select aria-label="Failure reason" value={reason} onChange={e=>setReason(e.target.value as DeliveryFailureReason)} className="mt-2 h-11 w-full rounded-lg border border-input bg-background px-3">{reasons.map(r=><option key={r} value={r}>{failureLabels[r]}</option>)}</select></label>}<label className="block text-sm font-medium">Note (optional)<textarea aria-label="Attempt note" value={note} maxLength={500} onChange={e=>setNote(e.target.value)} className="mt-2 min-h-24 w-full rounded-lg border border-input bg-background p-3"/><span className="mt-1 block text-xs text-muted-foreground">Add useful context for the delivery history. {note.length}/500</span></label><div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" disabled={pending} onClick={onClose} className="h-11 rounded-lg border border-border px-4 font-semibold">Cancel</button><button type="submit" disabled={pending} aria-busy={pending} className="h-11 rounded-lg bg-primary px-4 font-semibold text-primary-foreground disabled:opacity-60">{pending?'Recording…':delivered?'Record Delivered Attempt':'Record Failed Attempt'}</button></div></form></Frame>}
