'use client'

import { useEffect, useRef, useState } from 'react'
import { Loader2, X } from 'lucide-react'
import type { Customer } from '@/lib/api/customers'
import { normalizeMockUgandaPhone } from '@/lib/mock-customers'

export function CustomerFormDialog({ open, customer, submitting, serverError, onClose, onSave }: { open: boolean; customer?: Customer | null; submitting: boolean; serverError?: string | null; onClose: () => void; onSave: (value: { name: string | null; phone: string }) => void }) {
  const phoneRef = useRef<HTMLInputElement>(null)
  const [name, setName] = useState(''), [phone, setPhone] = useState(''), [error, setError] = useState('')
  useEffect(() => { if (open) { setName(customer?.name ?? ''); setPhone(customer?.phone ?? ''); setError(''); setTimeout(() => phoneRef.current?.focus(), 20) } }, [open, customer])
  useEffect(() => { if (!open) return; const key = (e: KeyboardEvent) => { if (e.key === 'Escape' && !submitting) onClose() }; document.addEventListener('keydown', key); return () => document.removeEventListener('keydown', key) }, [open, submitting, onClose])
  if (!open) return null
  const submit = (e: React.FormEvent) => { e.preventDefault(); if (!normalizeMockUgandaPhone(phone)) return setError('Enter a valid Uganda phone number.'); onSave({ name: name.trim() || null, phone: phone.trim() }) }
  return <div className="fixed inset-0 z-50 flex items-end justify-center sm:items-center sm:p-4" role="dialog" aria-modal="true" aria-labelledby="customer-form-title"><button className="absolute inset-0 bg-foreground/30" aria-label="Close dialog" onClick={onClose}/><div className="relative w-full rounded-t-2xl border border-border bg-card shadow-2xl sm:max-w-lg sm:rounded-2xl"><div className="flex items-center justify-between border-b border-border px-6 py-4"><h2 id="customer-form-title" className="font-semibold">{customer ? 'Edit customer' : 'Add Customer'}</h2><button type="button" onClick={onClose} disabled={submitting} aria-label="Close" className="rounded-lg p-2 hover:bg-secondary"><X className="size-4"/></button></div><form onSubmit={submit} noValidate><div className="space-y-5 px-6 py-5"><div><label htmlFor="customer-name" className="text-sm font-semibold">Customer name <span className="font-normal text-muted-foreground">(optional)</span></label><input id="customer-name" value={name} maxLength={160} onChange={(e) => setName(e.target.value)} placeholder="e.g. Sarah Nakato" className="mt-2 h-11 w-full rounded-lg border border-input bg-background px-3.5 text-sm outline-none focus:ring-2 focus:ring-ring/30"/></div><div><label htmlFor="customer-phone" className="text-sm font-semibold">Phone</label><input ref={phoneRef} id="customer-phone" type="tel" value={phone} onChange={(e) => { setPhone(e.target.value); setError('') }} placeholder="0772 123 456" aria-invalid={!!error} aria-describedby="customer-phone-help customer-phone-error" className="mt-2 h-11 w-full rounded-lg border border-input bg-background px-3.5 text-sm outline-none focus:ring-2 focus:ring-ring/30"/><p id="customer-phone-help" className="mt-1 text-xs text-muted-foreground">Use a Uganda number such as 0772… or +256…</p>{error && <p id="customer-phone-error" role="alert" className="mt-1 text-xs text-destructive">{error}</p>}</div>{serverError && <p role="alert" className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{serverError}</p>}</div><div className="flex justify-end gap-2 border-t border-border px-6 py-4"><button type="button" onClick={onClose} disabled={submitting} className="h-10 rounded-lg border border-border px-4 text-sm font-semibold">Cancel</button><button disabled={submitting || !phone.trim()} className="inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground disabled:opacity-50">{submitting && <Loader2 className="size-4 animate-spin"/>}{customer ? 'Save changes' : 'Add Customer'}</button></div></form></div></div>
}
